import { Dimensions, StyleSheet } from "react-native";
const { height, width } = Dimensions.get("window");

const styles = StyleSheet.create({
  container: {
    flex: 1,
    justifyContent: "flex-end",
    backgroundColor: "#5C0C91",
  },
  containerTwo: {
    flex: 1,
    justifyContent: "flex-end",
    backgroundColor: "#FD993E",
  },
  cover: {
    ...StyleSheet.absoluteFillObject,
    objectFit: "cover",
  },
  buttonWhite: {
    backgroundColor: "#fff",
    height: 55,
    alignItems: "center",
    justifyContent: "center",
    borderRadius: 15,
    marginHorizontal: 20,
    marginVertical: 10,
    borderWidth: 1,
    borderColor: "#fff",
    elevation: 4,
    shadowColor: "000",
  },
  buttonBlue: {
    backgroundColor: "#325ECF",
    height: 55,
    alignItems: "center",
    justifyContent: "center",
    borderRadius: 15,
    marginHorizontal: 20,
    marginVertical: 10,
    borderWidth: 1,
    borderColor: "#325ECF",
    elevation: 4,
    shadowColor: "000",
  },
  buttonTextBlack: {
    fontSize: 20,
    fontWeight: "600",
    color: "black",
    letterSpacing: 0.5,
  },
  buttonTextWhite: {
    fontSize: 20,
    fontWeight: "600",
    color: "white",
    letterSpacing: 0.5,
  },
  buttonContainer: {
    justifyContent: "center",
    height: height / 1.95,
    marginBottom: 20,
  },
  textInput: {
    height: 50,
    borderWidth: 1,
    // borderColor: "rgba(0, 0, 0, 0.2)",
    marginHorizontal: 20,
    marginVertical: 10,
    borderRadius: 15,
    paddingLeft: 10,
  },
  formButton: {
    backgroundColor: "#973EB5",
    height: 55,
    alignItems: "center",
    justifyContent: "center",
    borderRadius: 15,
    marginHorizontal: 20,
    marginVertical: 10,
    borderWidth: 1,
    borderColor: "#5D0D90",
    shadowColor: "#000",
    shadowOffset: {
      width: 0,
      height: 5,
    },
    shadowOpacity: 0.25,
    shadowRadius: 3.84,
    elevation: 5,
  },
  closeButtonContainer: {
    height: 40,
    width: 40,
    justifyContent: "center",
    alignSelf: "center",
    shadowColor: "#000",
    shadowOffset: {
      width: 0,
      height: 5,
    },
    shadowOpacity: 0.34,
    shadowRadius: 6.27,
    elevation: 1,
    backgroundColor: "white",
    alignItems: "center",
    borderRadius: 20,
    top: -20,
  },
});

export default styles;
